version: "3"

services:

  mongodb:
    container_name: ${DB_CONTAINER_NAME}
    image: "mongo:6.0"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}

    ports:
      - "27017:27017"

#    volumes:
#       - mongo_data:/data/db



